name: signalwavex
description: "A new Flutter project."

# To publish to pub.dev, remove or comment out this line.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0" # Ensure compatibility with Flutter SDK versioning

dependencies:
  flutter:
    sdk: flutter

  # For iOS-style icons
  cupertino_icons: ^1.0.8
  web_socket_channel:
  
  
  # For navigation in Flutter
  go_router: ^14.8.0
  flutter_screenutil: ^5.9.3
  riverpod: ^2.6.1
  fl_chart: ^0.68.0
  flutter_animate:
  flutter_svg:
  moment_dart:
  cached_network_image:
  intl:


  # for chart widget
  http:
  k_chart:
  uuid:
  syncfusion_flutter_charts:
    path: ./local_package/syncfusion_flutter_charts
  # flutter_otp:
  #   path: ./local_package/flutter_otp-master
  
  
  # for the crypto
  # crypto_market: 
  #   git:
  #     url: https://github.com/danoritic/crypto_market.git
  # card_swiper:
  # provider:
  # get:
  # candlesticks_plus:
  # coingecko_api:
  # sqflite:
  # dio:
  # shimmer:
  # onscreen_num_keyboard:
  # flutter_svg:
  # intl_phone_number_input:
  # flutter_animate:
  # uuid:
  # # fl_chart:
  # for the crypto ENDED.....

  # fancy nancy
  shimmer:
  dropdown_button2:
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  equatable: ^2.0.7
  shared_preferences: ^2.5.2
  internet_connection_checker_plus: ^2.7.1
  pretty_dio_logger: ^1.4.0
  google_sign_in: ^6.2.2
  flutter_localization: ^0.3.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.1.0
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter projects
  flutter_lints: ^4.0.0

flutter:

  generate: true
  uses-material-design: true

  # Asset directory configuration
  assets:
    - assets/
    # Image assets
    - assets/images/

    # Icon assets
    - assets/icons/

    # Sound assets
    - assets/sounds/
