name: signalwavex
description: "A new Flutter project."

# To publish to pub.dev, remove or comment out this line.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0" # Ensure compatibility with Flutter SDK versioning

dependencies:
  flutter:
    sdk: flutter

  # For iOS-style icons
  cupertino_icons: ^1.0.8
  
  # For navigation in Flutter
  go_router: ^14.8.0
  flutter_screenutil: ^5.9.3
  riverpod: ^2.6.1
  fl_chart: ^0.70.2


  # for chart widget
  http:
  k_chart:
  
  # for the crypto
  # crypto_market: 
  #   git:
  #     url: https://github.com/danoritic/crypto_market.git
  # card_swiper:
  # provider:
  # get:
  # candlesticks_plus:
  # coingecko_api:
  # sqflite:
  # dio:
  # shimmer:
  # onscreen_num_keyboard:
  # flutter_svg:
  # intl_phone_number_input:
  # flutter_animate:
  # uuid:
  # # fl_chart:
  # for the crypto ENDED.....

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter projects
  flutter_lints: ^4.0.0

flutter:
  # Ensures the Material Icons font is included for usage in the application.
  uses-material-design: true

  # Asset directory configuration
  assets:
    # Image assets
    - assets/images/

    # Icon assets
    - assets/icons/

    # Sound assets
    - assets/sounds/
