// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrrVZ-1pnvpMByXz2E5e_4f7IMepm1YoE',
    appId: '1:721127725533:web:3f6538c61615cf95da7e34',
    messagingSenderId: '721127725533',
    projectId: 'signalwalletx',
    authDomain: 'signalwalletx.firebaseapp.com',
    storageBucket: 'signalwalletx.firebasestorage.app',
    measurementId: 'G-EKH8GKHN1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMy1HFn2gBRo1cKnq94wm-uGxfHGK8b9A',
    appId: '1:721127725533:android:bf973fc9a3cf4717da7e34',
    messagingSenderId: '721127725533',
    projectId: 'signalwalletx',
    storageBucket: 'signalwalletx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY4eDEQ9YSfyl4FzrodKPRyNIeU9Qf0vI',
    appId: '1:721127725533:ios:6df3d639c9ea956ada7e34',
    messagingSenderId: '721127725533',
    projectId: 'signalwalletx',
    storageBucket: 'signalwalletx.firebasestorage.app',
    iosBundleId: 'com.example.signalwavex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY4eDEQ9YSfyl4FzrodKPRyNIeU9Qf0vI',
    appId: '1:721127725533:ios:6df3d639c9ea956ada7e34',
    messagingSenderId: '721127725533',
    projectId: 'signalwalletx',
    storageBucket: 'signalwalletx.firebasestorage.app',
    iosBundleId: 'com.example.signalwavex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrrVZ-1pnvpMByXz2E5e_4f7IMepm1YoE',
    appId: '1:721127725533:web:d91c0b7a8051f139da7e34',
    messagingSenderId: '721127725533',
    projectId: 'signalwalletx',
    authDomain: 'signalwalletx.firebaseapp.com',
    storageBucket: 'signalwalletx.firebasestorage.app',
    measurementId: 'G-838JVPFG67',
  );
}
